# Generated by Django 2.2.16 on 2020-12-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=12)),
                ('comments', models.TextField()),
            ],
        ),
    ]
