# Generated by Django 2.2.16 on 2020-11-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['categoria', 'name', '-update'], 'verbose_name': 'Informacion de producto', 'verbose_name_plural': 'Informacion de productos'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='background',
            field=models.ImageField(null=True, upload_to='categoriasBackGround', verbose_name='Imagen Fondo'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='image',
            field=models.ImageField(null=True, upload_to='categorias', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nameSpanish',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre Visible'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tags',
            field=models.TextField(null=True, verbose_name='Tags'),
        ),
    ]
