# Generated by Django 2.2.16 on 2020-12-07 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='comments',
            new_name='content',
        ),
    ]
