# Generated by Django 2.2.16 on 2020-12-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'ordering': ['-created'], 'verbose_name': 'Monitor', 'verbose_name_plural': 'Monitores'},
        ),
        migrations.AlterField(
            model_name='monitor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='image',
            field=models.ImageField(upload_to='monitores', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='tittle',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion'),
        ),
    ]
